### ISSUE TITLE
Occasional Core0 crashes.

### ISSUE THREAD

**Issue by magnusnordlander** [magnusnordlander/smart-lcc#3]
Core 0 occasionally gets an Mbed HardFault. I've traced this to _Balloc, but don't know yet exactly what triggers it. A long shot is printf:ing floats. This does not appear to be anywhere near as prevalent in debug builds (as in haven't been able to reproduce it yet) as in production builds.

**Comment by magnusnordlander** [comment]
Probably fixed in 1c081bf. Closing.

**Comment by magnusnordlander** [comment]
Not entirely fixed. It still crashes occasionally. More information soon.

**Comment by dkvdm** [comment]
Still following this project, thank you for your hard work!

**Comment by magnusnordlander** [comment]
Closing, turns out the crashes are on core 1, opened #7
